<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AbsensiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table("absensis")->insert([
            [
                'karyawan_id' => 1,
                'tanggal' => '2025-07-01',
                'jam_masuk' => '08:00:00',
                'jam_keluar' => '17:00:00',
                'foto_masuk' => 'photos/user1_in_20250701.jpg',
                'latitude_masuk' => '-6.3970', // Depok
                'longitude_masuk' => '106.8229', // Depok
                'foto_keluar' => 'photos/user1_out_20250701.jpg',
                'latitude_keluar' => '-6.3975',
                'longitude_keluar' => '106.8235',
                'status' => 'hadir',
                'lokasi' => 'Jl. Margonda Raya No.1, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 2,
                'tanggal' => '2025-07-01',
                'jam_masuk' => '08:15:00',
                'jam_keluar' => '16:45:00',
                'foto_masuk' => 'photos/user2_in_20250701.jpg',
                'latitude_masuk' => '-6.3800',
                'longitude_masuk' => '106.8300',
                'foto_keluar' => 'photos/user2_out_20250701.jpg',
                'latitude_keluar' => '-6.3805',
                'longitude_keluar' => '106.8305',
                'status' => 'hadir',
                'lokasi' => 'Jl. Nusantara Raya No.5, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 3,
                'tanggal' => '2025-07-01',
                'jam_masuk' => '09:00:00',
                'jam_keluar' => '17:30:00',
                'foto_masuk' => 'photos/user3_in_20250701.jpg',
                'latitude_masuk' => '-6.4000',
                'longitude_masuk' => '106.8000',
                'foto_keluar' => 'photos/user3_out_20250701.jpg',
                'latitude_keluar' => '-6.4005',
                'longitude_keluar' => '106.8005',
                'status' => 'terlambat',
                'lokasi' => 'Perumahan Sawangan Permai, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 1,
                'tanggal' => '2025-07-02',
                'jam_masuk' => '08:05:00',
                'jam_keluar' => '16:55:00',
                'foto_masuk' => 'photos/user1_in_20250702.jpg',
                'latitude_masuk' => '-6.3970',
                'longitude_masuk' => '106.8229',
                'foto_keluar' => 'photos/user1_out_20250702.jpg',
                'latitude_keluar' => '-6.3975',
                'longitude_keluar' => '106.8235',
                'status' => 'hadir',
                'lokasi' => 'Jl. Margonda Raya No.1, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 2,
                'tanggal' => '2025-07-02',
                'jam_masuk' => '08:00:00',
                'jam_keluar' => '17:00:00',
                'foto_masuk' => 'photos/user2_in_20250702.jpg',
                'latitude_masuk' => '-6.3800',
                'longitude_masuk' => '106.8300',
                'foto_keluar' => 'photos/user2_out_20250702.jpg',
                'latitude_keluar' => '-6.3805',
                'longitude_keluar' => '106.8305',
                'status' => 'hadir',
                'lokasi' => 'Jl. Nusantara Raya No.5, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 3,
                'tanggal' => '2025-07-02',
                'jam_masuk' => '08:30:00',
                'jam_keluar' => '17:00:00',
                'foto_masuk' => 'photos/user3_in_20250702.jpg',
                'latitude_masuk' => '-6.4000',
                'longitude_masuk' => '106.8000',
                'foto_keluar' => 'photos/user3_out_20250702.jpg',
                'latitude_keluar' => '-6.4005',
                'longitude_keluar' => '106.8005',
                'status' => 'hadir',
                'lokasi' => 'Perumahan Sawangan Permai, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 4,
                'tanggal' => '2025-07-01',
                'jam_masuk' => '08:45:00',
                'jam_keluar' => '17:15:00',
                'foto_masuk' => 'photos/user4_in_20250701.jpg',
                'latitude_masuk' => '-6.4100',
                'longitude_masuk' => '106.8150',
                'foto_keluar' => 'photos/user4_out_20250701.jpg',
                'latitude_keluar' => '-6.4105',
                'longitude_keluar' => '106.8155',
                'status' => 'hadir',
                'lokasi' => 'Jl. Tole Iskandar No.10, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 5,
                'tanggal' => '2025-07-01',
                'jam_masuk' => '08:00:00',
                'jam_keluar' => '16:00:00',
                'foto_masuk' => 'photos/user5_in_20250701.jpg',
                'latitude_masuk' => '-6.3700',
                'longitude_masuk' => '106.8400',
                'foto_keluar' => 'photos/user5_out_20250701.jpg',
                'latitude_keluar' => '-6.3705',
                'longitude_keluar' => '106.8405',
                'status' => 'hadir',
                'lokasi' => 'Grand Depok City, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 4,
                'tanggal' => '2025-07-02',
                'jam_masuk' => '08:40:00',
                'jam_keluar' => '17:10:00',
                'foto_masuk' => 'photos/user4_in_20250702.jpg',
                'latitude_masuk' => '-6.4100',
                'longitude_masuk' => '106.8150',
                'foto_keluar' => 'photos/user4_out_20250702.jpg',
                'latitude_keluar' => '-6.4105',
                'longitude_keluar' => '106.8155',
                'status' => 'hadir',
                'lokasi' => 'Jl. Tole Iskandar No.10, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 5,
                'tanggal' => '2025-07-02',
                'jam_masuk' => '08:10:00',
                'jam_keluar' => '16:15:00',
                'foto_masuk' => 'photos/user5_in_20250702.jpg',
                'latitude_masuk' => '-6.3700',
                'longitude_masuk' => '106.8400',
                'foto_keluar' => 'photos/user5_out_20250702.jpg',
                'latitude_keluar' => '-6.3705',
                'longitude_keluar' => '106.8405',
                'status' => 'hadir',
                'lokasi' => 'Grand Depok City, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 1,
                'tanggal' => '2025-07-03',
                'jam_masuk' => '08:00:00',
                'jam_keluar' => '17:00:00',
                'foto_masuk' => 'photos/user1_in_20250703.jpg',
                'latitude_masuk' => '-6.3970',
                'longitude_masuk' => '106.8229',
                'foto_keluar' => 'photos/user1_out_20250703.jpg',
                'latitude_keluar' => '-6.3975',
                'longitude_keluar' => '106.8235',
                'status' => 'hadir',
                'lokasi' => 'Jl. Margonda Raya No.1, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 2,
                'tanggal' => '2025-07-03',
                'jam_masuk' => '08:20:00',
                'jam_keluar' => '16:50:00',
                'foto_masuk' => 'photos/user2_in_20250703.jpg',
                'latitude_masuk' => '-6.3800',
                'longitude_masuk' => '106.8300',
                'foto_keluar' => 'photos/user2_out_20250703.jpg',
                'latitude_keluar' => '-6.3805',
                'longitude_keluar' => '106.8305',
                'status' => 'hadir',
                'lokasi' => 'Jl. Nusantara Raya No.5, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 3,
                'tanggal' => '2025-07-03',
                'jam_masuk' => '09:10:00',
                'jam_keluar' => '17:40:00',
                'foto_masuk' => 'photos/user3_in_20250703.jpg',
                'latitude_masuk' => '-6.4000',
                'longitude_masuk' => '106.8000',
                'foto_keluar' => 'photos/user3_out_20250703.jpg',
                'latitude_keluar' => '-6.4005',
                'longitude_keluar' => '106.8005',
                'status' => 'terlambat',
                'lokasi' => 'Perumahan Sawangan Permai, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 1,
                'tanggal' => '2025-07-04',
                'jam_masuk' => '08:00:00',
                'jam_keluar' => '17:00:00',
                'foto_masuk' => 'photos/user1_in_20250704.jpg',
                'latitude_masuk' => '-6.3970',
                'longitude_masuk' => '106.8229',
                'foto_keluar' => 'photos/user1_out_20250704.jpg',
                'latitude_keluar' => '-6.3975',
                'longitude_keluar' => '106.8235',
                'status' => 'hadir',
                'lokasi' => 'Jl. Margonda Raya No.1, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 2,
                'tanggal' => '2025-07-04',
                'jam_masuk' => '08:00:00',
                'jam_keluar' => '17:00:00',
                'foto_masuk' => 'photos/user2_in_20250704.jpg',
                'latitude_masuk' => '-6.3800',
                'longitude_masuk' => '106.8300',
                'foto_keluar' => 'photos/user2_out_20250704.jpg',
                'latitude_keluar' => '-6.3805',
                'longitude_keluar' => '106.8305',
                'status' => 'hadir',
                'lokasi' => 'Jl. Nusantara Raya No.5, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 3,
                'tanggal' => '2025-07-04',
                'jam_masuk' => '08:35:00',
                'jam_keluar' => '17:05:00',
                'foto_masuk' => 'photos/user3_in_20250704.jpg',
                'latitude_masuk' => '-6.4000',
                'longitude_masuk' => '106.8000',
                'foto_keluar' => 'photos/user3_out_20250704.jpg',
                'latitude_keluar' => '-6.4005',
                'longitude_keluar' => '106.8005',
                'status' => 'hadir',
                'lokasi' => 'Perumahan Sawangan Permai, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 4,
                'tanggal' => '2025-07-03',
                'jam_masuk' => '08:50:00',
                'jam_keluar' => '17:20:00',
                'foto_masuk' => 'photos/user4_in_20250703.jpg',
                'latitude_masuk' => '-6.4100',
                'longitude_masuk' => '106.8150',
                'foto_keluar' => 'photos/user4_out_20250703.jpg',
                'latitude_keluar' => '-6.4105',
                'longitude_keluar' => '106.8155',
                'status' => 'hadir',
                'lokasi' => 'Jl. Tole Iskandar No.10, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 5,
                'tanggal' => '2025-07-03',
                'jam_masuk' => '08:05:00',
                'jam_keluar' => '16:00:00',
                'foto_masuk' => 'photos/user5_in_20250703.jpg',
                'latitude_masuk' => '-6.3700',
                'longitude_masuk' => '106.8400',
                'foto_keluar' => 'photos/user5_out_20250703.jpg',
                'latitude_keluar' => '-6.3705',
                'longitude_keluar' => '106.8405',
                'status' => 'hadir',
                'lokasi' => 'Grand Depok City, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 4,
                'tanggal' => '2025-07-04',
                'jam_masuk' => '08:45:00',
                'jam_keluar' => '17:15:00',
                'foto_masuk' => 'photos/user4_in_20250704.jpg',
                'latitude_masuk' => '-6.4100',
                'longitude_masuk' => '106.8150',
                'foto_keluar' => 'photos/user4_out_20250704.jpg',
                'latitude_keluar' => '-6.4105',
                'longitude_keluar' => '106.8155',
                'status' => 'hadir',
                'lokasi' => 'Jl. Tole Iskandar No.10, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'karyawan_id' => 5,
                'tanggal' => '2025-07-04',
                'jam_masuk' => '08:15:00',
                'jam_keluar' => '16:20:00',
                'foto_masuk' => 'photos/user5_in_20250704.jpg',
                'latitude_masuk' => '-6.3700',
                'longitude_masuk' => '106.8400',
                'foto_keluar' => 'photos/user5_out_20250704.jpg',
                'latitude_keluar' => '-6.3705',
                'longitude_keluar' => '106.8405',
                'status' => 'hadir',
                'lokasi' => 'Grand Depok City, Depok',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
